// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZxWAQA1M-XCK6TmHi0odbcUnV1UV8EAo',
    appId: '1:652048446070:web:1dd55fa20efbf7ca982557',
    messagingSenderId: '652048446070',
    projectId: 'csan-poit',
    authDomain: 'csan-poit.firebaseapp.com',
    storageBucket: 'csan-poit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEqjxThEXOq3z3gWFrgqGMYNMMmKxBtA',
    appId: '1:652048446070:android:ca0b2650020e071d982557',
    messagingSenderId: '652048446070',
    projectId: 'csan-poit',
    storageBucket: 'csan-poit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3Cl-0aXcBVg8_v9qF0I7eKRBWi-PjFU',
    appId: '1:652048446070:ios:c198c81d5b100539982557',
    messagingSenderId: '652048446070',
    projectId: 'csan-poit',
    storageBucket: 'csan-poit.appspot.com',
    iosBundleId: 'by.bsuir.csan',
  );
}
